#!/usr/bin/env bash

# This script helps to clean a directory without deleting the files

# It sets all the contents of the `pwd` directory inside of a new directory
# (called `oldX` where X is a number). This is like a "trash" folder but attached
# to the current directory also a new "trash" folder is created each time `age`
# is run (incrementing the largest X number by 1) but only the files and
# directories that does not have a name like `oldX` are moved to the new
# `old` directory this helps organizing the trash temporally (all the contentes
# of oldN-1 are older than the contents of oldN).

# Example1: before age : `pwd`-(file1,file2,file3)
#           after  age : `pwd`-old1-(file1,file2,file3)

# Example2: before age : `pwd`--old1-(file1,file2,file3)
#                             |-(file5,folder1,file6)
#
#           after  age : `pwd`--old1-(file1,file2,file3)
#                             |-old2-(file5,folder1,file6)

# TODO:
# * Dynamic padding with 0:
#   * Numbers with less digits than the max age should padded with 0 to match the max age digit count
#   * Right now the padding is fixed and large (6):
#     * This causes problems when age is above 999999
#     * The padding is not efficient when max age is low

# * An option to fill the age gaps (possible when the user deleltes an old folder)

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace

die=false

# ---- flag parsing ----
for arg in "$@"; do
  case "$arg" in
  -d | --die) die=true ;;
  *)
    echo "Unknown option: $arg" >&2
    exit 1
    ;;
  esac
done

# ---- select files ----
if $die; then
  filesToAge=$(ls | grep -E '^old[0-9]+' || true)
  prefix=".old"
else
  filesToAge=$(ls | grep -Ev '^old[0-9]+' || true)
  prefix="old"
fi

if [ -z "$filesToAge" ]; then
  echo "Nothing to age"
  exit 0
fi

# ---- compute next age ----
currentAge=$(
  ls | grep "^${prefix}" |
    grep -E "^${prefix#\.}[0-9]+" |
    sed -E "s/^${prefix#\.}0*//" |
    sort -n |
    tail -1 || true
)

if [ -z "$currentAge" ]; then
  newAge=1
else
  ((newAge = currentAge + 1))
fi

newAgeDir="${prefix}$(printf "%06d" "$newAge")"

if $die; then
  echo "Happy $newAge death"
else
  echo "Happy $newAge birthday"
fi

mkdir "$newAgeDir"

# ---- move ----
OLD_IFS=$IFS
IFS=$'\n'
mv $filesToAge "$newAgeDir"
IFS=$OLD_IFS
