#!/usr/bin/env bash

vsync() {
  nvidia-settings --assign \
    "CurrentMetaMode=nvidia-auto-select +0+0 { ForceFullCompositionPipeline = $1 }"
}

distro_name=$(lsb_release -i | sed 's/.*:\s*//g')
case "$distro_name" in
Arch)
  current=$(nvidia-settings -tq CurrentMetaMode)

  if ! (echo "$current" | grep -q "ForceFullCompositionPipeline=On"); then
    vsync On
  fi

  # SCREEN_1=HDMI-0
  # SCREEN_2=DP-1
  SCREEN_0=eDP-1
  SCREEN_1=DP-2-1
  SCREEN_2=DP-2-3
  xrandr --output $SCREEN_0 --mode 1680x1050 --rotate inverted --output $SCREEN_1 --mode 1920x1080 --rotate inverted --right-of $SCREEN_0 --output $SCREEN_2 --mode 1920x1080 --rotate inverted --right-of $SCREEN_1
  xrandr --output $SCREEN_0 --mode 1680x1050 --rotate normal --output $SCREEN_1 --mode 1920x1080 --rotate normal --right-of $SCREEN_0 --output $SCREEN_2 --mode 1920x1080 --rotate normal --right-of $SCREEN_1
  brightctl 72000
  nitrogen --set-tiled --head=0 $WALLPAPER_FILE
  nitrogen --set-tiled --head=1 $WALLPAPER_FILE
  nitrogen --set-tiled --head=2 $WALLPAPER_FILE
  ;;
Ubuntu)
  DISPLAY_0=eDP
  DISPLAY_1=DisplayPort-1
  DISPLAY_2=DisplayPort-2
  xrandr --output $DISPLAY_0 --mode 1920x1080 --rotate inverted --output $DISPLAY_1 --mode 1920x1080 --rotate inverted --right-of $DISPLAY_0 --output $DISPLAY_2 --mode 1920x1080 --rotate inverted --right-of $DISPLAY_1
  xrandr --output $DISPLAY_0 --mode 1920x1080 --rotate normal --output $DISPLAY_1 --mode 1920x1080 --rotate normal --right-of $DISPLAY_0 --output $DISPLAY_2 --mode 1920x1080 --rotate normal --right-of $DISPLAY_1
  nitrogen --set-tiled --head=0 $WALLPAPER_FILE
  nitrogen --set-tiled --head=1 $WALLPAPER_FILE
  nitrogen --set-tiled --head=2 $WALLPAPER_FILE
  ;;
esac
xrandr --dpi 96
