#!/usr/bin/env bash

distro_name=$(lsb_release -i | sed 's/.*:\s*//g')
case "$distro_name" in
Arch)
  function vsync { nvidia-settings --assign CurrentMetaMode="nvidia-auto-select +0+0 { ForceFullCompositionPipeline = $@ }"; }
  [[ $(nvidia-settings -tq CurrentMetaMode | grep ForceFullCompositionPipeline=On) ]] && vsync Off || vsync On

  xrandr --output eDP-1 --mode 1920x1080 --rate 60 --output HDMI-0 --rotate inverted --output DP-1 --mode 1920x1080 --rotate inverted --left-of HDMI-0 &>/dev/null
  xrandr --output eDP-1 --mode 1920x1080 --rate 60 --output HDMI-0 --rotate normal --output DP-1 --mode 1920x1080 --rotate normal --left-of HDMI-0 &>/dev/null
  brightctl 72000
  nitrogen --set-tiled $WALLPAPER_FILE
  ;;
Ubuntu)
  DISPLAY_0=eDP
  DISPLAY_1=DisplayPort-1
  DISPLAY_2=DisplayPort-2
  xrandr --output $DISPLAY_0 --mode 1920x1080 --rotate inverted --output $DISPLAY_1 --mode 1920x1080 --rotate inverted --right-of $DISPLAY_0 --output $DISPLAY_2 --mode 1920x1080 --rotate inverted --right-of $DISPLAY_1
  xrandr --output $DISPLAY_0 --mode 1920x1080 --rotate normal --output $DISPLAY_1 --mode 1920x1080 --rotate normal --right-of $DISPLAY_0 --output $DISPLAY_2 --mode 1920x1080 --rotate normal --right-of $DISPLAY_1
  nitrogen --set-tiled --head=0 $WALLPAPER_FILE
  nitrogen --set-tiled --head=1 $WALLPAPER_FILE
  nitrogen --set-tiled --head=2 $WALLPAPER_FILE
  ;;
esac
xrandr --dpi 96
