#! /usr/bin/env bash

set -o xtrace # Trace the execution of the script (debug)

# Usage 'gitsyncer [directory where the local git repo will be or is located] [repo to sync]'

function gitsync() {
  git-http2ssh
  git add .
  git commit -m "$(cat /etc/hostname)"
  git pull
  git push
}

case $# in
2)
  dir=$1
  repo=$2
  if [ -d "$dir" ]; then
    cd "$dir"
    gitsync
  else
    root="$(dirname "$dir")"
    mkdir -p $root
    cd $root
    git clone $repo "$(basename "$dir")"
  fi
  ;;
*)
  echo "Wrong number of parameters"
  exit 1
  ;;
esac
