#!/usr/bin/env bash

set -ueo pipefail

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
source "$SCRIPT_DIR/lib/backup_lib.sh"

DATE="$(date +%F_%H-%M-%S)"

DRY_RUN="${DRY_RUN:-false}"
MAX_SNAPSHOT_AGE=100

if [[ $EUID -ne 0 ]]; then
    echo "Run with sudo..."
    exit 1
fi

##################
# Enable logging #
##################
setup_logging "bkp_01_02" "$DATE"

################
# Mount points #
################
BKP_01_01="/mnt/bkp_01_01"
BKP_01_01_DATA="$BKP_01_01/@"
BKP_01_02="/run/media/fede/bkp_01_02"
BKP_01_02_DATA="$BKP_01_02/@"
BKP_01_02_SNAPSHOTS="$BKP_01_02/@.snapshots"

#############
# Rsync cmd #
#############
setup_rsync

################
# Safety check #
################
check_mounts "$BKP_01_01" "$BKP_01_02"

setup_lock

##########
# Mirror #
##########
echo "# Mirroring bkp_01_01 to bkp_01_02"
"${RSYNC[@]}" "$BKP_01_01_DATA/" "$BKP_01_02_DATA/"

############
# SNAPSHOT #
############
echo "# Creating snapshot"
create_snapshot \
    "$BKP_01_02_DATA" \
    "$BKP_01_02_SNAPSHOTS" \
    "$DATE"

#######################
# PRUNE OLD SNAPSHOTS #
#######################
echo "# Checking snapshots older than $MAX_SNAPSHOT_AGE days"
check_snapshot_age \
    "$BKP_01_02_SNAPSHOTS" \
    "$MAX_SNAPSHOT_AGE"

##########
# Scrub  #
##########
echo "# Scrubbing mirror disk"
btrfs scrub start -B "$BKP_01_02"

################
# Disk health  #
################
echo "# Checking disk health"
$SCRIPT_DIR/check_disks_health || true

echo "Mirror completed: $DATE"
